package nl.rubium.efteling.common.event.entity;

public enum EventType {
    STATUSCHANGED,
    REQUESTEMPLOYEE,
    IDLE,
    VISITORSUNBOARDED,
    STEPINRIDELINE,
    WATCHINGFAIRYTALE,
    ARRIVEDATFAIRYTALE,
    EMPLOYEECHANGEDWORKPLACE,
    ORDERREADY,
    ORDERRECEIVED,
    WAITINGFORORDER
}
