version: '3.4'

services:

  park:
    container_name: park
    image: park
    depends_on:
      - kafka
    build:
      context: .
      dockerfile: park/Dockerfile
    environment:
      - spring_kafka_bootstrap-servers=kafka:9092
      - spring_kafka_consumer_bootstrap-servers=kafka:9092
    ports:
      - "49983:49983"

  rides:
    container_name: rides
    image: rides
    depends_on: 
      - park
      - kafka
    build:
      context: .
      dockerfile: rides/Dockerfile
    environment:
      - spring_kafka_bootstrap-servers=kafka:9092
      - spring_kafka_consumer_bootstrap-servers=kafka:9092
    ports:
      - "49981:49981"
    
  
  fairytales:
    container_name: fairytales
    image: fairytales
    depends_on: 
      - park
      - kafka
    build:
      context: .
      dockerfile: fairy-tales/Dockerfile
    environment:
      - spring_kafka_bootstrap-servers=kafka:9092
      - spring_kafka_consumer_bootstrap-servers=kafka:9092
    ports:
      - "49980:49980"

  stands:
    container_name: stands
    image: stands
    depends_on: 
      - park
      - kafka
    build:
      context: .
      dockerfile: stands/Dockerfile
    environment:
      - spring_kafka_bootstrap-servers=kafka:9092
      - spring_kafka_consumer_bootstrap-servers=kafka:9092
    ports:
      - "49982:49982"

  visitors:
    container_name: visitors
    image: visitors
    depends_on: 
      - park
      - rides
      - fairytales
      - stands
      - kafka
    restart: on-failure
    build:
      context: .
      dockerfile: visitors/Dockerfile
    environment:
      - spring_kafka_bootstrap-servers=kafka:9092
      - spring_kafka_consumer_bootstrap-servers=kafka:9092
    ports:
      - "49984:49984"
      
  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    depends_on:
      - zookeeper
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CREATE_TOPICS: events:10:1
    ports:
      - 9092:9092

  zookeeper:
    container_name: zookeeper
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181